import argparse
import os
import re


DEFAULT_ARCHIVE_NAME = "scripts.rpa"
DEFAULT_OUTPUT_NAME = "zzz_mod_choice_hints_generated.rpy"


def extract_choice_hints(data):
    labels = _find_labels(data)
    hints = {}

    for menu_match in re.finditer(rb"(?m)^\s*menu\s*(\w+)?\s*:", data):
        current_label = _label_before(labels, menu_match.start())
        menu_end = _next_label_or_eof(data, menu_match.end())
        menu_block = data[menu_match.start():menu_end]
        choice_matches = list(re.finditer(rb'"([^"]+)"\s*:', menu_block))

        for index, choice_match in enumerate(choice_matches):
            caption_bytes = choice_match.group(1)
            caption = caption_bytes.decode("utf-8", "ignore")
            if not _valid_caption(caption, caption_bytes):
                continue

            branch_start = choice_match.start()
            branch_end = choice_matches[index + 1].start() if index + 1 < len(choice_matches) else len(menu_block)
            branch_data = menu_block[branch_start:branch_end]
            effects = _extract_effects(branch_data)

            if effects:
                key = (current_label, caption)
                _merge_hint(hints, key, effects)

    return hints


def render_generated_hints(hints):
    lines = [
        "# Generated by extract_menu_hints_generic.py",
        "init -2 python:",
        "    GENERATED_CHOICE_HINTS = {",
    ]

    for label, caption in sorted(hints.keys()):
        hint = hints[(label, caption)]
        lines.append("        ('{}', '{}'): '{}',".format(_escape(label), _escape(caption), _escape(hint)))

    lines.append("    }")
    return "\n".join(lines) + "\n"


def run_extraction(archive_path, output_path):
    with open(archive_path, "rb") as archive_file:
        hints = extract_choice_hints(archive_file.read())

    with open(output_path, "w", encoding="utf-8") as output_file:
        output_file.write(render_generated_hints(hints))

    return len(hints)


def build_arg_parser():
    parser = argparse.ArgumentParser(description="Extract Ren'Py menu consequence hints from an archive-like file.")
    parser.add_argument("--game-path", help="Game folder used to derive default archive/output paths.")
    parser.add_argument("--archive", help="Input archive/script file path. Defaults to <game-path>/scripts.rpa.")
    parser.add_argument("--output", help="Output .rpy path. Defaults to <game-path>/zzz_mod_choice_hints_generated.rpy.")
    return parser


def resolve_paths(args):
    archive_path = args.archive
    output_path = args.output

    if args.game_path:
        archive_path = archive_path or os.path.join(args.game_path, DEFAULT_ARCHIVE_NAME)
        output_path = output_path or os.path.join(args.game_path, DEFAULT_OUTPUT_NAME)

    if not archive_path or not output_path:
        raise ValueError("Provide --archive and --output, or provide --game-path for defaults.")

    return archive_path, output_path


def main(argv=None):
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    try:
        archive_path, output_path = resolve_paths(args)
        count = run_extraction(archive_path, output_path)
    except Exception as exc:
        parser.error(str(exc))
        return 2

    print("Extracted {} choice hints to {}".format(count, output_path))
    return 0


def _find_labels(data):
    labels = []
    for match in re.finditer(rb"(?m)^\s*label\s+([a-zA-Z0-9_]+):", data):
        labels.append((match.start(), match.group(1).decode("utf-8", "ignore")))
    return labels


def _label_before(labels, position):
    current_label = "unknown"
    for label_position, label_name in labels:
        if label_position < position:
            current_label = label_name
        else:
            break
    return current_label


def _next_label_or_eof(data, position):
    next_label = re.search(rb"(?m)^\s*label\s+[a-zA-Z0-9_]+:", data[position:])
    return position + next_label.start() if next_label else len(data)


def _valid_caption(caption, caption_bytes):
    if len(caption) > 150 or len(caption) < 1:
        return False
    return not (b"{" in caption_bytes and b"}" not in caption_bytes)


def _extract_effects(branch_data):
    effects = []
    patterns = [
        rb"\$?\s*([a-zA-Z0-9_]+\s*(?:\+=|-=|=)\s*[a-zA-Z0-9_\"'\.]+)",
        rb"([a-zA-Z0-9_]+\.(?:append|remove|add)\([^\)]*\))",
        rb"(route_[a-zA-Z0-9_]+\s*=\s*(?:True|False))",
    ]

    for pattern in patterns:
        for match in re.finditer(pattern, branch_data):
            effect = match.group(1).decode("utf-8", "ignore").replace("$", "").strip()
            if effect not in effects:
                effects.append(effect)

    if not effects:
        jump_match = re.search(rb"jump\s+([a-zA-Z0-9_]+)", branch_data)
        if jump_match:
            effects.append("Jump -> " + jump_match.group(1).decode("utf-8", "ignore"))

    return effects


def _merge_hint(hints, key, effects):
    if key not in hints:
        hints[key] = "; ".join(effects)
        return

    existing = hints[key].split("; ")
    for effect in effects:
        if effect not in existing:
            existing.append(effect)
    hints[key] = "; ".join(existing)


def _escape(value):
    return str(value).replace("\\", "\\\\").replace("'", "\\'")


if __name__ == "__main__":
    raise SystemExit(main())
